dist: trusty
 
language: R
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

sudo: required

apt_packages:
  - gsl-bin
  - libgsl0-dbg
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev
  - r-cran-r.rsp
  - r-cran-covr
  - r-cran-testthat

before_install:
  - sudo add-apt-repository ppa:marutter/c2d4u -y
  - sudo apt-get update -q

repos:
  CRAN: http://cran.rstudio.com


after_success:
  - Rscript -e 'covr::codecov()'
