dist: trusty
 
language: R
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

sudo: required

apt_packages:
  - libgsl0-dbg
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev
  
r_packages:
  - devtools
  
repos:
  CRAN: http://cran.rstudio.com


after_success:
  - Rscript -e 'covr::codecov()'
